# Using Panads

import pandas as pd

salesdata=pd.read_csv("sales_data.csv")
print(salesdata)

salesdata.shape
salesdata.info()

# what is the total revenue from all sales?
salesdata['revenue']=salesdata['Quantity']*salesdata['Price']
print("Total revenue :-", salesdata['revenue'].sum())

# How mamy orders were places?
Totalorders=salesdata['OrderID'].count()
print(Totalorders)

#  How mamy total items were sold?
totalItems=salesdata['Quantity'].sum()
print(totalItems)

#  what is the total revenue generated by each category?
totalRevenue=salesdata.groupby('Category')['revenue'].sum()
print("Total Revenue by each category:-", totalRevenue)

# What is the total revenue generated by each product?

prodrevenue=salesdata.groupby('Product')['revenue'].sum()
print("Total revenue by product:-",prodrevenue  )


## Which product has the highest quantity sold?
highquan=salesdata.groupby('Product')['Quantity'].sum()
highp=highquan.idxmax()
highq=highquan.max()
print(f"{highp}: {highq}")


## Which customer spent the more money?
customer=salesdata.groupby('Customer')['revenue'].sum()

print (f"{customer.idxmax()}:{customer.max()}")

# what is the total revenue by each date?
daterevenue=salesdata.groupby('Date')["revenue"].sum()
print(daterevenue)

# What is the total revenue between two given dates?
print(type(salesdata["Date"]))
salesdata['Date']=pd.to_datetime(salesdata['Date'])
startdate=input("Enter your start date(yy-mm-dd):-")
enddate=input("Enter your end date:-")

trevenue=salesdata[(salesdata['Date']>=startdate) &(salesdata['Date']<=enddate)]
print("Total Revenue between two dates:-" , trevenue['revenue'].sum())

# Export all orders under "Electronic Category" into a new csv file

electronic_cat=salesdata[salesdata['Category']=="Electronics"]
electronic_cat.to_csv("electronics_pan.csv", index=False)
print("\n successfully exported!")