## Reading Data
with open("sales_data.csv", "r") as data:
    lines=data.readlines()
    print(lines)


newData=[]
for line in lines[1:]:
    field=line.strip().split(",")
    field[5]=int(field[5])
    field[6]=int(field[6])
    newData.append(field)
print(newData)

## what is the total revenue from all sales?
Totalrevenue = 0
for row in newData:
    quantity=row[5]
    price=row[6]
    Totalrevenue+=quantity*price
print("Total Revenue is :₹ ", Totalrevenue)   

## How mamy orders were places?
TotalOrders=len(newData)
print("Total Orders were:", TotalOrders)

##  How mamy total items were sold?
TotalItems=0
for row in newData:
    TotalItems += row[5]
print("Total Items were:", TotalItems) 

## what is the total revenue generated by each category?
category_revenue={}
for row in newData:
    category=row[4]
    revenue=row[5]*row[6]
    if category in category_revenue:
        category_revenue[category]+=revenue
    else:
        category_revenue[category]=revenue  

for cat,rev in category_revenue.items():
    print(f"{cat}:{rev}")

## What is the total revenue generated by each product?
TotalPrevenue={}
for row in newData:
    product=row[3]
    revenue=row[5]*row[6]
    if product in TotalPrevenue:
        TotalPrevenue[product]+=revenue
    else:
        TotalPrevenue[product]=revenue
[print(f"{pro}:{rev}") for pro,rev in TotalPrevenue.items()] 

## Which product has the highest quantity sold?
product_quantity={}
for row in newData:
    product=row[3]
    quantity=row[5]
    if product in product_quantity:
        product_quantity[product]+=quantity
    else:
        product_quantity[product]=quantity
higestSold=None
max_quantity =0
for pro,quan in product_quantity.items():
    if quan>max_quantity:
        max_quantity=quan
        highestSold=pro
print("Product sold by highest quantity is:", f"{highestSold}:{max_quantity}")   

## Which customer spent the more money?
cust_spend={}
for row in newData:
    customer=row[2]
    spend=row[5]*row[6]
    if customer in cust_spend:
        cust_spend[customer]+=spend
    else:
        cust_spend[customer]=spend

print(cust_spend)        
Customer=None
max_spend =0
for cus,spend in cust_spend.items():
    if spend>max_spend:
        max_spend=spend
        Customer=cus
print("more money spent by customer :", f"{Customer}:{max_spend}")  

## what is the total revenue by each date?
daily_revenue={}
for row in newData:
    date=row[1]
    revenue=row[5]*row[6]
    if date in daily_revenue:
        daily_revenue[date]+=revenue
    else:
        daily_revenue[date]=revenue
print("Daily revenue is ",daily_revenue)   
[print(f"{date}: {rev}") for date,rev in daily_revenue.items()]   

## What is the total revenue between two given dates?
from datetime import datetime
start=input("Enter your start date(yyy-mmm-ddd):")
end=input("Enter your end date(yyy-mmm-ddd):")

start_d=datetime.strptime(start,"%Y-%m-%d")
end_d=datetime.strptime(end,"%Y-%m-%d")

Total_d_revenue=0
for row in newData:
    order_date=datetime.strptime(row[1],"%Y-%m-%d")

    if start_d<=order_date<=end_d:

       Total_d_revenue +=row[5]*row[6]
print("revenue from", start, "and", end ,"is", Total_d_revenue)

## Export all orders under "Electronic Category" into a new csv file

elect_file=open("electronic.csv","w")
elect_file.write("OrderID,Date,Customer,Product,Category,Quantity,Price\n")
for row in newData:
    if row[4]=="Electronics":
        row_str=",".join([str(item) for item in row])
        elect_file.write(row_str + "\n")
elect_file.close()

print("All electrical products saved into csv file")















